# UTS-2 My Songs for You

Untuk orang yang aku cintai, sayangnya perlu keajaiban untuk kita bisa bersama. Lagu ini mewakili keresahanku selama ini.

{{< video https://www.youtube.com/watch?v=2rB_83prClo>}}, with lyrics

Reality Club - Finding a Catholic Man to Love the Love of My Life 

[Verse 1]
I'm in a pickle
I've found the love of my life
But if I ever want to make her my wife
That's when the problems will arise

[Verse 2]
She's so gorgeous, won't you come and see?
But she can't be with someone like me
I pray that there's a miracle for me
Or else we simply can never be

[Chorus]
So I'm finding a Catholic man
To love the love of my life
When I'm old and grey I hope you'll be happy
Either way

[Verse 3]
Shе's got a smile that'll melt you in your seat
Shе's got wits to make you move your feet
Alas the universe has me beat
Pushed apart just as soon as we meet

[Verse 4]
She's got the beauty and she's got the mind
The best damn person that you'll ever find
I wish that she could stay as mine
Oh God, won't you give me a sign?

[Chorus]
So I'm finding a Catholic man
To love the love of my life
When I'm old and grey I hope you'll be happy
Either way
I'm finding a Catholic man
To love the love of my life
When I'm old and grey I hope you'll be happy
Either way
(Alright)

[Instrumental]

[Chorus]
So I'm finding a Catholic man
To love the love of my life
When I'm old and grey I hope you'll be happy
Either way
I'm finding a Catholic man
To love the love of my life
When I'm old and grey I hope you'll be happy
Either way

[Outro]
When I'm old and grey you know I'll still love you
Anyways



Entah apa yang takdir rencanakan untuk kita di masa mendatang, aku bersyukur dan berterima kasih atas memori indah yang telah kau berikan.

{{< video https://www.youtube.com/watch?v=0vbe_kIAHxI>}}, with lyrics

Di depan teras rumah
Fana merah jambu, ku berdua
Momen-momen tak palsu
Air tuhan turun, aromamu

Tersalurkan aliran syaraf buntu
Martin tua media pembuka

Berdansa sore hariku
Sejiwa alam dan duniamu
Melebur sifat kakuku

Hal bodoh jadi lucu
Obrolan tak perlu kala itu
Oh tersalurkan aliran syaraf buntu
Martin tua media pembuka

Berdansa sore hariku
Sejiwa alam dan duniamu
Melebur sifat kakuku
Rasanya tak cukup waktu
Terlalu cepat berlalu
Soreku nyaman denganmu

Menarilah, menarilah
Menarilah denganku
Genggam tangan cokelatku
Berputar-putar denganku
Menarilah denganku
Menarilah, menarilah

Tersalurkan aliran syaraf buntu
Martin tua media pembuka
Tersalurkan aliran syaraf buntu
Martin tua media pembuka
Media pembuka

Berdansa sore hariku
Sejiwa alam dan duniamu
Melebur sifat kakuku
Rasanya tak cukup waktu
Terlalu cepat berlalu
Soreku nyaman denganmu

Oh Menarilah, menarilah
Oh Menarilah denganku
Genggam tangan cokelatku
Berputar - putar denganku
Menarilah denganku
Menarilah