---
title: "UTS-4 My SHAPE"
subtitle: "Piagam Diri"
author: "Ahmad Syafiq"
format: html
---

## Pernyataan Misi Pribadi

> Misi saya adalah menggunakan perspektif akademisi yang transenden untuk merancang pendidikan yang bermakna, memberikan harapan, dan membuka potensi orang lain. Saya berdedikasi untuk menjadi sosok yang peka, menciptakan intervensi positif dalam pengembangan komunitas melalui keterbukaan pikiran.

## Kekuatan Khas

* **VIA Strength #1:** Humor
* **VIA Strength #2:** Hope
* **Feedback Teman:** Aku bisa melihat situasi dan kondisi dalam bentuk *big picture*, tidak *fixated* pada satu dua hal dan bisa *take into consideration* hal lainnya yang mungkin terkesan *negligible*. Hal ini membantuku dalam membuat keputusan yang lebih baik.

## Nilai Inti & Gairah

* **Nilai Inti #1:** Openmindedness
* **Nilai Inti #2:** Education
* **Saya bersemangat tentang:** * Isu lingkungan
    * Pengembangan komunitas
    * Pendidikan dan pengajaran
    * Neuroscience

## Keterampilan Utama

* **Hard Skills:**
    * Programming
    * Computer Networking
    * Database Management
    * English
    * Content Writing
    * Curriculum Design
* **Soft Skills:**
    * Communication
    * Collaboration
    * Empathy
    * Problem Solving
    * Critical Thinking
    * Public Speaking

## Profil Kepribadian

* **Tipe MBTI:** INFP
* **Gaya Kerja yang Disukai:** Fleksibel dan Tenang

## Pelajaran Hidup Kunci

* Dari cerita yang aku berikan pada tugas sebelumnya, saya belajar bahwa masa lalu, seaneh atau sesulit apa pun itu, tidak perlu disesali.
* Dari pengalaman mengajar, saya belajar bersyukur telah lahir di keluarga yang mengedepankan pendidikan.